#cloud-config

# Update system and install basic packages
package_update: true
package_upgrade: true

packages:
  - curl
  - wget
  - vim
  - git
  - htop
  - net-tools
  - unzip
  - jq
  - socat
  - conntrack
  - ipset

# System configuration
timezone: UTC
preserve_hostname: false

# Enable IP forwarding (required for Kubernetes)
write_files:
  - path: /etc/sysctl.d/99-kubernetes.conf
    content: |
      net.ipv4.ip_forward = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.bridge.bridge-nf-call-ip6tables = 1
    permissions: '0644'
  - path: /etc/modules-load.d/k8s.conf
    content: |
      br_netfilter
    permissions: '0644'

# Run commands on first boot
runcmd:
  - modprobe br_netfilter
  - sysctl --system
  - systemctl enable ssh
  - systemctl start ssh
  - echo "Cloud-init setup complete" > /var/log/cloud-init-complete.log